spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
  
  rabbitmq:
    host: 192.168.126.130
    port: 5672
    username: admin
    password: admin  
server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true #开启重试
  
ribbon:
  MaxAutoRetries: 1

item-service:
  ribbon:
    MaxAutoRetriesNextServer: 2
